
# Example config file

# Data server endpoint
server_host: localhost
server_port: 27812

# Admin server endpoint
admin_server_host: localhost
admin_server_port: 2781

# Data directory
data_dir: $HOME/var/quiu/

# Autoload all channels present in ${data_dir}/channel.index
# The alternative is to load them as requested
autorecover_channels: true
