
# Example config file


# Server endpoint

server_host: localhost
server_port: 27812


# Data directory

data_dir: $HOME/var/quiu/


# Autoload all channels present in ${data_dir}/channel.index
# The alternative is to load them as requested

autorecover_channels: true
